# デフォルト値
DEFAULT_COURT_COUNT = 2
DEFAULT_SKILL_MATCHING_ENABLED = True
ELO_K_FACTOR = 32
INITIAL_SKILL_POINTS = 50.0

# 制約値
MIN_PLAYERS_FOR_MATCH = 4
MAX_COURTS = 10
MAX_MATCHES_PER_GENERATION = 10
MIN_MATCHES_PER_GENERATION = 1

# データファイルパス
DATA_FILE_PATH = "data/pickle_pair_data.json" 